# Generated by Django 3.0 on 2019-12-06 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField()),
                ('delivery_date', models.DateTimeField()),
                ('creation_date', models.DateTimeField(auto_now=True, help_text='Fecha de creacion')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('delivery_date', models.DateTimeField()),
                ('creation_date', models.DateTimeField(auto_now=True, help_text='Fecha de creacion')),
                ('project', models.ForeignKey(help_text='Proyecto relacionado', on_delete=django.db.models.deletion.CASCADE, to='api.Project')),
                ('user', models.ForeignKey(help_text='Usuario relacionado', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
